---
gw_network: 192.168.2.0

dhcp_self: 192.168.2.1
dhcp_lower: 192.168.2.2
dhcp_upper: 192.168.2.200

domain: texsaw
domain_address: 10.176.169.100
hostname: cardboard

dns_SOA: 2016110401

int_if: bge0
ext_if: re0

boot_fname:
boot_next:

ntp:
- pool.ntp.org

staticHosts:
  wap:
    mac: 44:94:fc:39:50:ea
    addr: 192.168.2.2
    name: wap

stub-zones:
  UTD:
    name: utdallas.edu
    private: true
    localZone: 10.in-addr.arpa
    addresses:
      - 10.180.15.160
      - 10.182.70.107
